import { CourseInfo } from '@/types/courseType';

// export const coursesData: Record<string, CourseInfo[]> = {
//     ED: [{
//         image: "https://m1r.ai/53CdY.svg",
//         courseName: "นวัตกรรมการศึกษา",
//         description: "เรียนรู้เทคโนโลยีและวิธีการสอนสมัยใหม่",
//         courseID: "ED813001",
//         category: "Innovation",
//         date: "2024",
//         faculty: "คณะศึกษาศาสตร์",
//       },  {
//         image: "https://m1r.ai/53CdY.svg",
//         courseName: "นวัตกรรมการศึกษา",
//         description: "เรียนรู้เทคโนโลยีและวิธีการสอนสมัยใหม่",
//         courseID: "ED813001",
//         category: "Innovation",
//         date: "2024",
//         faculty: "คณะศึกษาศาสตร์",
//       },  
//         {
//           image: "https://m1r.ai/3YbL.svg",
//           courseName: "นวัตกรรมการศึกษา",
//           description: "เรียนรู้เทคโนโลยีและวิธีการสอนสมัยใหม่",
//           courseID: "ED813001",
//           category: "Innovation",
//           date: "2024",
//           faculty: "คณะศึกษาศาสตร์",
//         },{
//           image: "https://m1r.ai/5KDKN.svg",
//           courseName: "นวัตกรรมการศึกษา",
//           description: "เรียนรู้เทคโนโลยีและวิธีการสอนสมัยใหม่",
//           courseID: "ED813001",
//           category: "Innovation",
//           date: "2024",
//           faculty: "คณะศึกษาศาสตร์",
//         },{
//           image: "https://m1r.ai/KSTcJ.svg",
//           courseName: "นวัตกรรมการศึกษา",
//           description: "เรียนรู้เทคโนโลยีและวิธีการสอนสมัยใหม่",
//           courseID: "ED813001",
//           category: "Innovation",
//           date: "2024",
//           faculty: "คณะศึกษาศาสตร์",
//         },{
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: "นวัตกรรมการศึกษา",
//           description: "เรียนรู้เทคโนโลยีและวิธีการสอนสมัยใหม่",
//           courseID: "ED813001",
//           category: "Innovation",
//           date: "2024",
//           faculty: "คณะศึกษาศาสตร์",
//         },  
//       ],
//       EN: [
//         {
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: "Digital Engineering",
//           description: "พื้นฐานการออกแบบระบบดิจิทัลเทสสสสสสสสสสสสสสสสสสสสสสส",
//           courseID: "EN813001",
//           category: "Digital",
//           date: "2024",
//           faculty: "คณะวิศวกรรมศาสตร์",
//         },{
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: "Digital Engineering",
//           description: "พื้นฐานการออกแบบระบบดิจิทัล",
//           courseID: "EN813001",
//           category: "Digital",
//           date: "2024",
//           faculty: "คณะวิศวกรรมศาสตร์",
//         },{
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: "Digital Engineering",
//           description: "พื้นฐานการออกแบบระบบดิจิทัล",
//           courseID: "EN813001",
//           category: "Digital",
//           date: "2024",
//           faculty: "คณะวิศวกรรมศาสตร์",
//         },{
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: "Digital Engineering",
//           description: "พื้นฐานการออกแบบระบบดิจิทัล",
//           courseID: "EN813001",
//           category: "Digital",
//           date: "2024",
//           faculty: "คณะวิศวกรรมศาสตร์",
//         },{
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: " Sera",
//           description: "พื้นฐานการออกแบบระบบดิจิทัล",
//           courseID: "EN814",
//           category: "Digital",
//           date: "2024",
//           faculty: "คณะวิศวกรรมศาสตร์",
//         }
//         // เพิ่มคอร์สเพิ่มเติม...
//       ],
//       SC: [
//         {
//           image: "/animate/warning-animate.svg",
//           courseName: "Data Science Fundamentals",
//           description: "พื้นฐานวิทยาศาสตร์ข้อมูล",
//           courseID: "SC813001",
//           category: "Data Science",
//           date: "2024",
//           faculty: "คณะวิทยาศาสตร์",
//         },
//         // เพิ่มคอร์สเพิ่มเติม...
//       ],
//       HS: [
//         {
//           image: "/animate/warning-animate.svg",
//           courseName: "Data Science Fundamentals",
//           description: "พื้นฐานวิทยาศาสตร์ข้อมูล",
//           courseID: "HU813001",
//           category: "Data Science",
//           date: "2024",
//           faculty: "คณะมนุษยศาสตร์",
//         },
        
//       ],
//   };

// export const coursesData: Record<string, CourseInfo[]> = {
//   ED: [
//       {
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: "นวัตกรรมการศึกษา",
//           description: "เรียนรู้เทคโนโลยีและวิธีการสอนสมัยใหม่เรียนรู้เทคโนโลยีและวิธีม่",
//           courseID: "ED813001",
//           category: "Innovation",
//           date: "2024",
//           faculty: "คณะศึกษาศาสตร์",
//       },
//       {
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: "การศึกษาเพื่ออนาคต",
//           description: "สำรวจแนวทางการศึกษาในศตวรรษที่ ",
//           courseID: "ED813002",
//           category: "Future Education",
//           date: "2024", 
//           faculty: "คณะศึกษาศาสตร์",
//       }, {
//         image: "https://m1r.ai/53CdY.svg",
//         courseName: "นวัตกรรมการศึกษา",
//         description: "สำรวจแนวทางการศึกษาในศตวรรษที่ 21 ยใหม่เรียนรู้เทคโนโลยีและวิธีม่ ยใหม่เรียนรู้เทคโนโลยีและวิธีม่่",
//         courseID: "ED813001",
//         category: "Innovation",
//         date: "2024",
//         faculty: "คณะศึกษาศาสตร์",
//     }
//   ],
//   EN: [
//       {
//           image: "https://m1r.ai/53CdY.svg",
//           courseName: "Digital Engineering",
//           description: "พื้นฐานการออกแบบระบบดิจิทัล",
//           courseID: "EN813001",
//           category: "Digital",
//           date: "2024",
//           faculty: "คณะวิศวกรรมศาสตร์",
//       },
//       {
//           image: "https://m1r.ai/6FgW8D.svg",
//           courseName: "Advanced Digital Engineering",
//           description: "เทคนิคขั้นสูงในการออกแบบระบบดิจิทัล",
//           courseID: "EN813002",
//           category: "Digital",
//           date: "2024",
//           faculty: "คณะวิศวกรรมศาสตร์",
//       },
//       {
//           image: "https://m1r.ai/3YrI5J.svg",
//           courseName: "Cybersecurity Fundamentals",
//           description: "การป้องกันภัยคุกคามทางไซเบอร์",
//           courseID: "EN813003",
//           category: "Cybersecurity",
//           date: "2024",
//           faculty: "คณะวิศวกรรมศาสตร์",
//       },
//   ],
//   SC: [
//       {
//           image: "https://m1r.ai/wgK3V8.svg",
//           courseName: "Data Science Fundamentals",
//           description: "พื้นฐานวิทยาศาสตร์ข้อมูล",
//           courseID: "SC813001",
//           category: "Data Science",
//           date: "2024",
//           faculty: "คณะวิทยาศาสตร์",
//       },
//       {
//           image: "https://m1r.ai/jdL4K5.svg",
//           courseName: "Machine Learning Basics",
//           description: "เรียนรู้พื้นฐานของการเรียนรู้ของเครื่อง",
//           courseID: "SC813002",
//           category: "Machine Learning",
//           date: "2024",
//           faculty: "คณะวิทยาศาสตร์",
//       },
//   ],
//   HS: [
//       {
//           image: "https://m1r.ai/gA4B9J.svg",
//           courseName: "Data Science Fundamentals",
//           description: "พื้นฐานวิทยาศาสตร์ข้อมูล",
//           courseID: "HU813001",
//           category: "Data Science",
//           date: "2024",
//           faculty: "คณะมนุษยศาสตร์",
//       },
//       {
//           image: "https://m1r.ai/qX6Z3K.svg",
//           courseName: "Philosophy of Data Science",
//           description: "สำรวจปรัชญาในวิทยาศาสตร์ข้อมูล",
//           courseID: "HU813002",
//           category: "Philosophy",
//           date: "2024",
//           faculty: "คณะมนุษยศาสตร์",
//       },
//   ],
// };
