import {
    Cog,
    GraduationCap,
    Code,
    FlaskConical,
    Users,
    Stethoscope,
    BookOpen,
    Microscope,
    Leaf,
    Pill,
    Shield,
    Building,
    Paintbrush,
    Globe,
    DollarSign,
    Calculator,
    Laptop,
    Languages,
    Scale,
    TestTubeDiagonal,
    Binary,
    Clipboard,
    Briefcase,
  } from "lucide-react";
  import type { Faculty } from "@/types/faculty";
  
  export const FACULTY_DATA: Faculty[] = [
    {
        id: "ED",
        name: "คณะศึกษาศาสตร์",
        nameEn: "Faculty of Education",
        description: "เรียนรู้ศาสตร์แห่งการศึกษา พัฒนาบุคลากรทางการศึกษา",
        courseCount: 12,
        image: "/images/faculties/education.jpg",
        icon: GraduationCap,
        accent: "from-orange-100 to-yellow-100",
        borderAccent: "group-hover:border-orange-300",
      },
      {
        id: "EN",
        name: "คณะวิศวกรรมศาสตร์",
        nameEn: "Faculty of Engineering",
        description: "พัฒนาเทคโนโลยีและนวัตกรรมทางวิศวกรรม เพื่อสร้างสรรค์และแก้ไขปัญหาสังคมในมิติต่าง ๆ",
        courseCount: 15,
        image: "/images/faculties/engineering.jpg",
        icon: Cog,
        accent: "from-red-100 to-red-200",
        borderAccent: "group-hover:border-red-300",
      },
      {
        id: "SC",
        name: "คณะวิทยาศาสตร์",
        nameEn: "Faculty of Science",
        description: "สำรวจและวิจัยเพื่อพัฒนาองค์ความรู้ด้านวิทยาศาสตร์ และนำไปใช้ในการแก้ปัญหาเชิงสังคมและอุตสาหกรรม",
        courseCount: 20,
        image: "/images/faculties/science.jpg",
        icon: FlaskConical,
        accent: "from-yellow-50 to-yellow-100",
        borderAccent: "group-hover:border-yellow-200",
      },
      {
        id: "AG",
        name: "คณะเกษตรศาสตร์",
        nameEn: "Faculty of Agriculture",
        description: "ศึกษาวิธีการเกษตรที่ทันสมัย พัฒนาอุตสาหกรรมการเกษตรเพื่อความมั่นคงทางอาหาร",
        courseCount: 18,
        image: "/images/faculties/agriculture.jpg",
        icon: Leaf,
        accent: "from-green-50 to-green-100",
        borderAccent: "group-hover:border-green-200",
      },
      {
        id: "LI",
        name: "สถาบันภาษา",
        nameEn: "Language Institute",
        description: "พัฒนาทักษะภาษาสำหรับการศึกษาและการทำงาน",
        image: "/images/faculties/interdisciplinary.jpg",
        icon: Languages,
        accent: "from-orange-50 to-orange-100",
        borderAccent: "group-hover:border-orange-200",
      },
      {
        id: "CM",
        name: "วิทยาลัยบัณฑิตศึกษาการจัดการ",
        nameEn: "College of Management",
        description: "เสริมทักษะการจัดการและการเป็นผู้นำ",
        image: "/images/faculties/management.jpg",
        icon: Briefcase,
        accent: "from-blue-50 to-blue-100",
        borderAccent: "group-hover:border-blue-200",
      },
      {
        id: "GE",
        name: "สถาบันการสอนวิชาศึกษาทั่วไป",
        nameEn: "General Education Institute",
        description: "พัฒนาทักษะความรู้รอบตัวและการคิดเชิงวิพากษ์",
        image: "/images/faculties/general_education.jpg",
        icon: BookOpen,
        accent: "from-yellow-50 to-yellow-100",
        borderAccent: "group-hover:border-yellow-200",
      },
      {
        id: "CP",
        name: "วิทยาลัยการคอมพิวเตอร์",
        nameEn: "College of Computer Science",
        description: "ศึกษาเทคโนโลยีและนวัตกรรมด้านคอมพิวเตอร์ เพื่อรองรับความต้องการในโลกยุคดิจิทัล",
        image: "/images/faculties/computer_science.jpg",
        icon: Code,
        accent: "from-purple-50 to-purple-100",
        borderAccent: "group-hover:border-purple-200",
      },
      {
        id: "NU",
        name: "คณะพยาบาลศาสตร์",
        nameEn: "Faculty of Nursing",
        description: "พัฒนาบุคลากรการพยาบาลที่มีคุณภาพ เพื่อการดูแลและส่งเสริมสุขภาพที่ยั่งยืน",
        courseCount: 10,
        image: "/images/faculties/nursing.jpg",
        icon: Stethoscope,
        accent: "from-blue-50 to-cyan-100",
        borderAccent: "group-hover:border-cyan-200",
      },
      {
        id: "MD",
        name: "คณะแพทยศาสตร์",
        nameEn: "Faculty of Medicine",
        description: "มุ่งเน้นการศึกษาด้านการแพทย์และการรักษา",
        courseCount: 25,
        image: "/images/faculties/medicine.jpg",
        icon: Users,
        accent: "from-green-50 to-green-100",
        borderAccent: "group-hover:border-green-200",
      },
      {
        id: "HS",
        name: "คณะมนุษยศาสตร์และสังคมศาสตร์",
        nameEn: "Faculty of Humanities and Social Sciences",
        description: "ศึกษาและพัฒนาทางด้านมนุษยศาสตร์และสังคม",
        courseCount: 30,
        image: "/images/faculties/humanities.jpg",
        icon: BookOpen,
        accent: "from-gray-50 to-gray-100",
        borderAccent: "group-hover:border-gray-200",
      },
      {
        id: "MT",
        name: "คณะเทคนิคการแพทย์",
        nameEn: "Faculty of Medical Technology",
        description: "เน้นการศึกษาวิทยาศาสตร์การแพทย์และเทคนิคที่ทันสมัย",
        courseCount: 15,
        image: "/images/faculties/medical_technology.jpg",
        icon: Microscope,
        accent: "from-blue-50 to-blue-100",
        borderAccent: "group-hover:border-blue-200",
      },
      {
        id: "GS",
        name: "บัณฑิตวิทยาลัย",
        nameEn: "Graduate School",
        description: "ส่งเสริมการศึกษาระดับบัณฑิตศึกษา",
        courseCount: 5,
        image: "/images/faculties/graduate_school.jpg",
        icon: Building,
        accent: "from-gray-50 to-gray-100",
        borderAccent: "group-hover:border-gray-200",
      },
      {
        id: "PH",
        name: "คณะสาธารณสุขศาสตร์",
        nameEn: "Faculty of Public Health",
        description: "พัฒนาบุคลากรด้านสาธารณสุขเพื่อบริการสังคม",
        courseCount: 22,
        image: "/images/faculties/public_health.jpg",
        icon: Clipboard,
        accent: "from-pink-50 to-pink-100",
        borderAccent: "group-hover:border-pink-200",
      },
      {
        id: "DE",
        name: "คณะทันตแพทยศาสตร์",
        nameEn: "Faculty of Dentistry",
        description: "ศึกษาและฝึกฝนด้านทันตแพทยศาสตร์",
        courseCount: 12,
        image: "/images/faculties/dentistry.jpg",
        icon: Shield,
        accent: "from-purple-50 to-purple-100",
        borderAccent: "group-hover:border-purple-200",
      },
      {
        id: "PHM",
        name: "คณะเภสัชศาสตร์",
        nameEn: "Faculty of Pharmacy",
        description: "ศึกษาวิทยาศาสตร์การผลิตยา และการให้บริการด้านเภสัชกรรมเพื่อสุขภาพที่ดีของสังคม",
        courseCount: 18,
        image: "/images/faculties/pharmacy.jpg",
        icon: Pill,
        accent: "from-green-50 to-green-100",
        borderAccent: "group-hover:border-green-200",
      },
      {
        id: "TC",
        name: "คณะเทคโนโลยี",
        nameEn: "Faculty of Technology",
        description: "พัฒนาเทคโนโลยีสมัยใหม่สู่การใช้งานในหลากหลายสาขา",
        courseCount: 16,
        image: "/images/faculties/technology.jpg",
        icon: Laptop,
        accent: "from-red-50 to-red-100",
        borderAccent: "group-hover:border-red-200",
      },
      {
        id: "VM",
        name: "คณะสัตวแพทยศาสตร์",
        nameEn: "Faculty of Veterinary Science",
        description: "ศึกษาวิทยาศาสตร์สัตวแพทย์และสุขภาพสัตว์",
        courseCount: 14,
        image: "/images/faculties/veterinary_medicine.jpg",
        icon: Stethoscope,
        accent: "from-blue-50 to-blue-100",
        borderAccent: "group-hover:border-blue-200",
      },
      {
        id: "AR",
        name: "คณะสถาปัตยกรรมศาสตร์",
        nameEn: "Faculty of Architecture",
        description: "สร้างสรรค์ศิลปะและวิชาชีพด้านสถาปัตยกรรม",
        courseCount: 17,
        image: "/images/faculties/architecture.jpg",
        icon: Building,
        accent: "from-brown-50 to-brown-100",
        borderAccent: "group-hover:border-brown-200",
      },
      {
        id: "BA",
        name: "คณะบริหารธุรกิจและการบัญชี",
        nameEn: "Faculty of Business Administration and Accounting",
        description: "พัฒนาธุรกิจและการจัดการบัญชี",
        courseCount: 20,
        image: "/images/faculties/business.jpg",
        icon: DollarSign,
        accent: "from-teal-50 to-teal-100",
        borderAccent: "group-hover:border-teal-200",
      },
      {
        id: "FA",
        name: "คณะศิลปกรรมศาสตร์",
        nameEn: "Faculty of Fine Arts",
        description: "มุ่งเน้นการสร้างสรรค์ด้านศิลปกรรม",
        courseCount: 13,
        image: "/images/faculties/fine_arts.jpg",
        icon: Paintbrush,
        accent: "from-gray-200 to-gray-400",
        borderAccent: "group-hover:border-gray-700",
      },
      {
        id: "LA",
        name: "คณะนิติศาสตร์",
        nameEn: "Faculty of Law",
        description: "ศึกษาและพัฒนากฎหมายเพื่อสังคม",
        courseCount: 19,
        image: "/images/faculties/law.jpg",
        icon: Scale,
        accent: "from-yellow-50 to-yellow-100",
        borderAccent: "group-hover:border-yellow-200",
      },
      {
        id: "EC",
        name: "คณะเศรษฐศาสตร์",
        nameEn: "Faculty of Economics",
        description: "ศึกษาและวิจัยด้านเศรษฐศาสตร์",
        courseCount: 14,
        image: "/images/faculties/economics.jpg",
        icon: Calculator,
        accent: "from-yellow-50 to-yellow-100",
        borderAccent: "group-hover:border-yellow-200",
      },
      {
        id: "ID",
        name: "คณะสหวิทยาการ",
        nameEn: "Faculty of Interdisciplinary Studies",
        description: "ศึกษาและบูรณาการศาสตร์ต่าง ๆ เข้าด้วยกัน",
        courseCount: 11,
        image: "/images/faculties/interdisciplinary.jpg",
        icon: TestTubeDiagonal,
        accent: "from-indigo-50 to-indigo-100",
        borderAccent: "group-hover:border-indigo-200",
      }
  ];
